### ISSUE TITLE
Chuẩn bị môi trường Dev

### ISSUE THREAD

**Issue by TRUYEN-PRD** [prdlab/CANAL-Ver1.0#11]
1.Tạo 1 bộ source trên GitHub prdlab/Canal-Ver1.0 bộ source để dev.
2.Tạo triển khai bộ source lên máy 192.168.100.21 vào thư mục /var/www/html/prd/

**Comment by thosuperman** [comment]
Please add this line to your local hosts file
192.168.100.21 canal.proteusion.com

**Comment by TRUYEN-PRD** [comment]
■Sơ đồ tài liệu
-Requirement
https://drive.google.com/open?id=0B_6rpN8LpQMDNFpGc3l0bkNlTGM
-Layout Design
https://drive.google.com/open?id=0B_6rpN8LpQMDaS10a0RieXI1ZU0
-DB Design
https://drive.google.com/open?id=0B_6rpN8LpQMDSjl3V1NTUTY1Mm8
-Detail Desing
https://drive.google.com/open?id=0B_6rpN8LpQMDQzBHbWVWeWI3YU0
-Schedule
https://drive.google.com/open?id=0B_6rpN8LpQMDZVNvYzEwZnpiVEE
▲Mỗi ngày vui lòng cập nhận schedule trước khi về.

■Chú ý:
-Trong khi dev nếu detail desing có thay đổi thì ghi chú vào và thay đổi màu chử phần thay đổi.

**Comment by thosuperman** [comment]
- [ ] Tạo 1 bộ source trên GitHub prdlab/Canal-Ver1.0 bộ source để dev

- [ ] Tạo triển khai bộ source lên máy 192.168.100.21 vào thư mục /var/www/html/prd/

**Comment by TRUYEN-PRD** [comment]
![image](https://cloud.githubusercontent.com/assets/26053010/23992563/eefd00c4-0a6f-11e7-8bab-b7d14e503909.png)

■Schedule cho toàn hệ thống:
https://drive.google.com/open?id=0B_6rpN8LpQMDMllrYXdjSXRGT0U
