### ISSUE TITLE
Submenu

### ISSUE THREAD

**Issue by TRUYEN-PRD** [prdlab/CANAL-Ver1.0#13]
■ System Addmin menu
![image](https://cloud.githubusercontent.com/assets/26053010/24641682/c4a80c90-192b-11e7-9438-83d89746247a.png)

1. Bỏ mục Profile, setting, logout. Thay thế chức năng logout như thiết kế (Nằm dưới mục ○ENVIRONMENT SETTING).
2. Bỏ menu Operator , hiển thị 2 menu riêng rẽ (List Operator và Create Operator)
   Màn hình hiển thị đầu tiên sau khi login là List Operator.
3. Bỏ menu [Bamboo user]

■Canal Operator
![image](https://cloud.githubusercontent.com/assets/26053010/24642350/0d096722-1931-11e7-9ef6-3712419e5ad2.png)
1. Bỏ mục Profile, setting, logout. Thay thế chức năng logout như thiết kế (Nằm dưới mục ○USD/BTC RATE INPUT).
2.  Màn hình hiển thị đầu tiên sau khi login là  [ WAITING DEPOSIT LIST]

**Comment by TRUYEN-PRD** [comment]
![image](https://cloud.githubusercontent.com/assets/26053010/25930132/9bdd7992-362e-11e7-9269-e172ef59699e.png)

1. Thay chử [BAMBOO USER] thành [HELLO <Full Name>]

**Comment by thosuperman** [comment]
![2017-05-11_112826](https://cloud.githubusercontent.com/assets/17564259/25932679/fbcd9a18-363c-11e7-9fed-77683e7aed1d.png)
