### ISSUE TITLE
SendBTCInfo

### ISSUE THREAD

**Issue by TRUYEN-PRD** [prdlab/CANAL-Ver1.0#17]
1. Access http://192.168.100.23:8888/en/admin/login 
2. Setting TestNet Bitcore Wallet Service URL: http://192.168.100.22:3232/bws/api
3. Access http://192.168.100.23:8889/en/admin/login
4. Setting TestNet Bitcore Wallet Service URL : http://192.168.100.22:3232/bws/api
5. Access http://canal.proteusion.com/admin/options#wallet setting
   TESTNET: Insight API url = http://test-insight.canalpay.ml/insight-api
   TESTNET: Main wallet client API url = http://192.168.100.23:5588/api
   TESTNET: Payout wallet client API url = http://192.168.100.23:5589/api
6. Tạo order mới.
7. Send BTC 
【Error】
1. BTC không đi vào wallet chỉ định.
   (Có thể BTC Address được sinh ra không phải của Main Wallet được chỉ định.)

**Comment by thosuperman** [comment]
This problem solved by restart wallet server. We must restart it by following command

> pm2 status
![2017-04-05_174634](https://cloud.githubusercontent.com/assets/17564259/24702175/d76897c6-1a27-11e7-9daf-b51318f7d327.png)

> pm2 restart (id1, id2...)
